// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint: import.meta.env['VITE_API_ENDPOINT'],
      region: import.meta.env['VITE_API_REGION'],
      defaultAuthMode: import.meta.env['VITE_API_AUTH_MODE'],
      apiKey: import.meta.env['VITE_API_KEY']
    }
  }
}

export default config
